/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tamar
 */
public class menuPenilaian extends javax.swing.JPanel {

    /**
     * Creates new form menuPenilaian
     */
    public Statement st;
    public ResultSet rs;
    Map<String, String> alternatifMap = new HashMap<>();
    Connection c = Koneksi.sambung_ke_db();
    public menuPenilaian() {
       initComponents();
       loadAlternatif();
       TampilDataPenilaian();
    }
    
     private void loadAlternatif() {
        try {
            st = c.createStatement();
            String sql = "SELECT id, nama FROM alternatif";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                String id = rs.getString("id");
                String nama = rs.getString("nama");
                cmbAlt.addItem(nama); // Tambahkan nama ke JComboBox
                alternatifMap.put(nama, id); // Simpan pasangan nama dan id ke dalam Map
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat memuat data alternatif: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
     
    private void TampilDataPenilaian(){
        try {
            st = c.createStatement();
            String sql = "SELECT k.id, a.nama, k.ipk, k.tes_pemrograman, k.kemampuan_mengajar, k.nilai_referensi, k.kerjasama "
                    + "FROM kriteria k "
                    + "JOIN alternatif a ON k.id_alternatif = a.id";
            rs = st.executeQuery(sql);

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No");
            model.addColumn("Nama");
            model.addColumn("IPK");
            model.addColumn("Tes Pemrograman");
            model.addColumn("Kemampuan Mengajar");
            model.addColumn("Nilai Referensi");
            model.addColumn("Kerjasama");

            int no = 1;

            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] data = {
                    no++,
                    rs.getString("nama"),
                    rs.getDouble("ipk"),
                    rs.getDouble("tes_pemrograman"),
                    rs.getDouble("kemampuan_mengajar"),
                    rs.getDouble("nilai_referensi"),
                    rs.getDouble("kerjasama")
                };
                model.addRow(data);
            }
            tblPenilaian.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat memuat data penilaian: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

     private void bersihPenilaian() {
        cmbAlt.setSelectedIndex(-1);
        txtIpk.setText("");
        txtTestPemrograman.setText("");
        txtKemampuanMengajar.setText("");
        txtNilaiReferensi.setText("");
        txtKerjasama.setText("");
        
        btnSimpan.setText("Simpan");
        cmbAlt.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbAlt = new javax.swing.JComboBox<>();
        txtIpk = new javax.swing.JTextField();
        txtKerjasama = new javax.swing.JTextField();
        txtNilaiReferensi = new javax.swing.JTextField();
        txtKemampuanMengajar = new javax.swing.JTextField();
        txtTestPemrograman = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenilaian = new javax.swing.JTable();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setText("Tambah Penilaian");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel3.setText("IPK");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setText("Nilai Refrensi");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel5.setText("Kerjasama");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel6.setText("Tes Pemrograman");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel7.setText("Kemampuan Mengajar");

        cmbAlt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nama" }));

        tblPenilaian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "IPK", "Tes Pemrograman", "Kemampuan Mengajar", "Nilai Refrensi", "Kerjasama"
            }
        ));
        tblPenilaian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPenilaianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPenilaian);

        btnBatal.setBackground(new java.awt.Color(0, 102, 255));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(0, 204, 51));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbAlt, 0, 278, Short.MAX_VALUE)
                                    .addComponent(txtIpk)
                                    .addComponent(txtTestPemrograman)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtKemampuanMengajar)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNilaiReferensi)
                                    .addComponent(txtKerjasama, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNilaiReferensi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIpk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtKerjasama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTestPemrograman, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtKemampuanMengajar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
          try {
        st = c.createStatement();
        if (cmbAlt.getSelectedItem() == null ||
            txtIpk.getText().equals("") ||
            txtTestPemrograman.getText().equals("") ||
            txtKemampuanMengajar.getText().equals("") ||
            txtNilaiReferensi.getText().equals("") ||
            txtKerjasama.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong", "Validasi Data", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String selectedNama = cmbAlt.getSelectedItem().toString();
        String idAlternatif = alternatifMap.get(selectedNama);

        if (btnSimpan.getText().equals("Simpan")) {
            // Cek apakah id_alternatif sudah ada di tabel kriteria
            String cek = "SELECT * FROM kriteria WHERE id_alternatif = '" + idAlternatif + "'";
            rs = st.executeQuery(cek);
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Penilaian untuk alternatif ini sudah ada. Tidak bisa menambahkan kembali.");
            } else {
                String sql = "INSERT INTO kriteria (id_alternatif, ipk, tes_pemrograman, kemampuan_mengajar, nilai_referensi, kerjasama) VALUES ('"
                        + idAlternatif + "', '"
                        + Double.parseDouble(txtIpk.getText()) + "', '"
                        + Double.parseDouble(txtTestPemrograman.getText()) + "', '"
                        + Double.parseDouble(txtKemampuanMengajar.getText()) + "', '"
                        + Double.parseDouble(txtNilaiReferensi.getText()) + "', '"
                        + Double.parseDouble(txtKerjasama.getText()) + "')";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
                bersihPenilaian();
                TampilDataPenilaian();
            }
        } else {
            String update = "UPDATE kriteria SET ipk = '" + Double.parseDouble(txtIpk.getText())
                    + "', tes_pemrograman = '" + Double.parseDouble(txtTestPemrograman.getText())
                    + "', kemampuan_mengajar = '" + Double.parseDouble(txtKemampuanMengajar.getText())
                    + "', nilai_referensi = '" + Double.parseDouble(txtNilaiReferensi.getText())
                    + "', kerjasama = '" + Double.parseDouble(txtKerjasama.getText())
                    + "' WHERE id_alternatif = '" + idAlternatif + "'";
            st.executeUpdate(update);
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            bersihPenilaian();
            TampilDataPenilaian();
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblPenilaianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPenilaianMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblPenilaian.getSelectedRow();
        if (selectedRow != -1) {
            cmbAlt.setSelectedItem(tblPenilaian.getValueAt(selectedRow, 1).toString());
            txtIpk.setText(tblPenilaian.getValueAt(selectedRow, 2).toString());
            txtTestPemrograman.setText(tblPenilaian.getValueAt(selectedRow, 3).toString());
            txtKemampuanMengajar.setText(tblPenilaian.getValueAt(selectedRow, 4).toString());
            txtNilaiReferensi.setText(tblPenilaian.getValueAt(selectedRow, 5).toString());
            txtKerjasama.setText(tblPenilaian.getValueAt(selectedRow, 6).toString());

            cmbAlt.setEnabled(false);
            btnSimpan.setText("Ubah");
        }
    }//GEN-LAST:event_tblPenilaianMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        bersihPenilaian();
    }//GEN-LAST:event_btnBatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbAlt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPenilaian;
    private javax.swing.JTextField txtIpk;
    private javax.swing.JTextField txtKemampuanMengajar;
    private javax.swing.JTextField txtKerjasama;
    private javax.swing.JTextField txtNilaiReferensi;
    private javax.swing.JTextField txtTestPemrograman;
    // End of variables declaration//GEN-END:variables
}
